name: datum-pithos
services:
  web:
    build:
      context: ./frontend/BlazorApp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:8000/api/v1/
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - USERNAME=admin
      - PASSWORD=admin
    volumes:
      - ./db:/db
